import Head from 'next/head';
import Link from 'next/link';
import { Container, Row, Col, Button } from 'react-bootstrap';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Image Upload App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Row className="justify-content-center">
          <Col xs={10} sm={8} md={6}>
            <h1 className="text-center my-5">Welcome to Secure Login</h1>
            <div className="d-flex justify-content-center">
              <Link href="/login">
                <Button variant="primary" className="mr-3">
                  Login
                </Button>
              </Link>
              <Link href="/register">
                <Button variant="success">Register</Button>
              </Link>
            </div>
          </Col>
        </Row>
      </Container>
    </>
  );
}
